bookguardian/urls.py
from django.conf.urls import handler404
from django.urls import path

from . import views

app_name = "bookguardian"

handler404 = views.Custom404View.as_view()

urlpatterns = [
    # BookGuardian
    path("", views.LadinPage.as_view(), name="ladinpage"),
    path("index/", views.HomeList.as_view(), name="index"),
    path("settings/", views.PageConfig.as_view(), name="settings"),
    path("newbook/", views.PageNewBook.as_view(), name="newbook"),
    path("book/<int:pk>/", views.PageDetailBook.as_view(), name="bookdetail"),
    path("book-update/<int:pk>/", views.PageUpdateBook.as_view(), name="bookupdate"),
    path("book-delete/<int:pk>/", views.PageDeleteBook.as_view(), name="bookdelete"),
    # # User
    # path("login/", views.LoginRoute.as_view(), name="login"),
    # path("register/", views.RegisterUser.as_view(), name="register-user"),
    # path("logout/", views.custom_logout, name="logout"),
]

setup/urls.py
from allauth.socialaccount.providers.google.urls import (
    urlpatterns as google_urlpatterns,
)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

social_urlpatterns = [
    path("", include(google_urlpatterns)),
]

from django.views.static import serve

urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include("bookguardian.urls")),
    path("user/", include("userauths.urls")),
    path("accounts/", include(social_urlpatterns)),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns = [] + urlpatterns

userauths/urls.py
from django.urls import path

from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView.as_view(), name="sign-up"),
    path("sign-in/", views.LoginView.as_view(), name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
]

bookguardian/models.py
from django.db import models

from userauths.models import User


class BookGuardian(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    profile_image = models.ImageField(
        upload_to="profileImage/%Y/%m/", blank=True, null=True
    )
    book_image = models.ImageField(
        upload_to="bookImage/%Y/%m/", blank=False, null=False
    )
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    author_book = models.CharField(
        max_length=100, blank=True, null=True, default="desconhecido"
    )
    category = models.CharField(
        default=("G", "Generico"),
        max_length=50,
        # Status
        choices=(
            ("G", "Generico"),
            ("F", "Ficcao"),
            ("R", "Romance"),
            ("T", "Terro"),
            ("FA", "Fantasia"),
            ("NF", "Nao ficcao"),
            ("MHQ", "Manga e HQ"),
        ),
        blank=True,
        null=True,
    )
    read = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)

bookguardian/forms.py
from django import forms


class PositionForm(forms.Form):
    position = forms.CharField()

bookguardian/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from . import models


class LadinPage(ListView):
    model = models.BookGuardian
    template_name = "ladinpage.html"
    context_object_name = "bookguardian"


class PageNewBook(LoginRequiredMixin, CreateView):
    model = models.BookGuardian
    fields = ["book_image", "title", "description", "category", "author_book", "read"]
    success_url = reverse_lazy("bookguardian:index")  #
    template_name = "addBook.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PageNewBook, self).form_valid(form)


class PageDetailBook(LoginRequiredMixin, DetailView):
    model = models.BookGuardian
    context_object_name = "bookguardian"
    template_name = "bookPage.html"


class PageUpdateBook(LoginRequiredMixin, UpdateView):
    model = models.BookGuardian
    context_object_name = "bookguardian"
    fields = ["book_image", "title", "description", "category", "author_book", "read"]
    success_url = reverse_lazy("bookguardian:index")  #
    template_name = "updateBook.html"


class PageDeleteBook(LoginRequiredMixin, DeleteView):
    model = models.BookGuardian
    context_object_name = "bookguardian"
    success_url = reverse_lazy("bookguardian:index")
    template_name = "bookguardian_confirm_delete.html"

    def get_queryset(self):
        owner = self.request.user
        return self.model.objects.filter(user=owner)


class PageConfig(ListView):
    model = models.BookGuardian
    template_name = "configPage.html"
    context_object_name = "bookguardian"


class HomeList(LoginRequiredMixin, ListView):
    model = models.BookGuardian
    template_name = "index.html"
    context_object_name = "bookguardian"
    login_url = "/login/"

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            queryset = models.BookGuardian.objects.filter(user=user)
        else:

            return reverse_lazy("bookguardian:ladinpage")
        return queryset


# # User
# class LoginRoute(LoginView):
#     template_name = "login.html"
#     fields = "__all__"
#     redirect_authenticated_user = True

#     def get_success_url(self):
#         return reverse_lazy("bookguardian:index")


# class RegisterUser(FormView):
#     template_name = "register.html"
#     form_class = UserCreationForm
#     redirect_authenticated_user = True
#     success_url = reverse_lazy("bookguardian:index")

#     def form_valid(self, form):
#         user = form.save()
#         if user is not None:
#             login(self.request, user)
#         return super(RegisterUser, self).form_valid(form)

#     def get(self, *args, **kwargs):
#         if self.request.user.is_authenticated:
#             return redirect("bookguardian:index")
#         return super(RegisterUser, self).get(*args, **kwargs)

#     def get_form(self, form_class=None):
#         form = super(RegisterUser, self).get_form(form_class)

#         form.fields["username"].widget.attrs["placeholder"] = "Digite o seu User"
#         form.fields["password1"].widget.attrs["placeholder"] = "Digite a sua Senha"
#         form.fields["password1"].widget.attrs["id"] = "password1"
#         form.fields["password2"].widget.attrs["placeholder"] = "Confirme a Senha"
#         form.fields["password2"].widget.attrs["id"] = "password2"
#         return form


# def custom_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse_lazy("bookguardian:ladinpage"))


class Custom404View(View):
    def get(self, request, exception=None):
        return render(request, "404.html", {}, status=404)

bookguardian/templates/addBook.html
{% extends "base.html" %} {% block title %} Adicionar Livro {% endblock title %}
{% block content %}
    <div class="rowContainer">
        <div id="newBookDiv">
            <h2>Cadastro de Livro</h2>
            <form id="newBookForm" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="titleInp">Título:</label>
                <input type="text" id="titleInp" name="title" placeholder="Titulo" required>

                <label for="authorInp">Autor(a):</label>
                <input type="text" id="authorInp" name="author_book" placeholder="Autor" required>

                <label for="descriptionInp">Descrição:</label>
                <textarea id="descriptionInp" name="description"
                placeholder="Descricao" required rows="4" style="resize: vertical;"></textarea>

                <label for="imageInp">Imagem da capa:</label>
                <input type="file" id="imageInp" name="book_image">

                <div id="formSelects">
                    <label for="genre">Gênero:</label>
                    <select id="genre" name="category">
                        <option value="G">Genérico</option>
                        <option value="F">Ficção cientifica</option>
                        <option value="R">Romance</option>
                        <option value="T">Terror</option>
                        <option value="NF">Não ficção</option>
                        <option value="FA">Fantasia</option>
                        <option value="MHQ">Manga e HQ</option>
                    </select>


                    <label for="status">Status:</label>
                    <select id="status" name="read">
                        <option value="True">Já li</option>
                        <option value="False">Quero ler</option>
                    </select>
                </div>
                <div id="addBtnsNavegation">
                    <button type="submit" id="addBook">Adicionar</button>
                    <button id="cancelBook">Cancelar</button>
                </div>
            </form>
        </div>

    </div>
{% endblock content %}

bookguardian/templates/bookPage.html
{% extends "base.html" %}
 {% block title %}
 Book Page
{% endblock title %}

{% block content %}
<div id="bookPage">
    <img src="{{ bookguardian.book_image.url }}" alt="capa">
    <div id="bookMainContainer">
        <div id="informacoes">
            <h1 id="titulo">{{ bookguardian.title }}</h1>
            <h3>Por: <span id="autor">{{ bookguardian.author_book }}</span></h3>
            <h3>Descrição:</h3>
            <p id="descricao">{{ bookguardian.description }}</p>
            <h3>Status: {% if bookguardian.read %}<span id="status" class="read" style="font-weight: 800;">Já li </span>{% else %}<span id="status" class="nonRead">Não li</span>{% endif %}</h3>
            <h3>Gênero: <span>
                {% if bookguardian.category == 'G' %}
                    Genérico
                {% elif bookguardian.category == 'F' %}
                    Ficção
                {% elif bookguardian.category == 'R' %}
                    Romance
                {% elif bookguardian.category == 'T' %}
                    Terror
                {% elif bookguardian.category == 'FA' %}
                    Fantasia
                {% elif bookguardian.category == 'NF' %}
                    Nâo ficção
                {% elif bookguardian.category == 'MHQ' %}
                    Manga e HQ
                {% else %}
                    Desconhecido
                {% endif %}
            </span></h3>

        </div>
        <div id="bookEdit">
            <a href=" {% url "bookguardian:bookupdate"  pk=bookguardian.pk %} ">
                <button id="editarLivro">editar <i class="fi
                fi-rr-edit"></i></button>
            </a>
            <a href="{% url "bookguardian:bookdelete" pk=bookguardian.pk %}">
                <button id="excluirLivro">excluir <i class="fi
                fi-rr-trash"></i></button>
            </a>
        </div>
    </div>
</div>
{% endblock content %}

bookguardian/templates/bookguardian_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<div class="card-body" id="deleteContainer">
    <form method="POST">
        {% csrf_token %}
        <h1>
            Deseja realmente apagar o livro: <b>{{ bookguardian.title }}</b> ?
        </h1>
        <div class="header-bar" id="btnNavDelete">
            <a class="deletBtn" id="cancel" href="{% url 'bookguardian:index' %}">&#8592; Voltar</a>
            <button class="deletBtn" id="delete" type="submit" value="Delete">Apagar</button>
        </div>
    </form>
</div>

{% endblock content %}

bookguardian/templates/configPage.html
{% extends 'base.html' %}

{% block title %} Configurações {% endblock title %}
{% block content %}

    <div id="config">
        <h3>Tema</h3>
        <div class="configConainerRow">
            <div class="optnT">
                <div style="background-color: #0e1120;" id="darkTheme" class="choiceTheme">
                    <h5 style="background-color: #2d3242;"><p style="color:
                    #fff;">________  <br> ________<br> ________</p></h5>
                </div>
                <input type="radio" name="themeRadio" id="darkRadio">
                <label for="darkRadio">Escuro</label>
            </div>

            <div class="optnT">
                <div style="background-color: #f6f6f6;" id="lightTheme" class="choiceTheme">
                    <h5 style="background-color: #fff;"><p style="color:
                    #000;">________  <br> ________<br> ________</p></h5>
                </div>
                <input type="radio" name="themeRadio" id="lightRadio">
                <label for="lightRadio">Claro</label>
            </div>

            <div class="optnT">
                <div id="autoTheme" class="choiceTheme">
                    <h5><p><span style="color: #000">____</span>____<br> <span style="color: #000">____</span>____<br> <span style="color: #000">____</span>____</p></h5></h5>
                </div>
                <input type="radio" name="themeRadio" id="autoRadio">
                <label for="autoRadio">Automático</label>
            </div>

        </div>

            <h3 style="margin-top: 8rem;">Cor</h3>
        <div class="configConainerRow">
            <button id="pink" style="background-color: rgb(255, 59, 163);">Rosa</button>
            <button id="blue" style="background-color: #0ebbff;">Azul</button>
        </div>
    </div>
    <div class="configConainerRow" id="configNavBtn">
        <button id="saveConfig">
            Voltar
        </button>
    </div>
    {% endblock content %}

bookguardian/templates/index.html
{% extends "base.html" %} {% block title %} Pagina Inicial {% endblock title %}
{% load static %}
{% block content %}
<header>
    <div id="mainHeader">
        <h1 id="logo">Book Guardian</h1>
        <div id="searchDiv">
            <input
                type="text"
                name="search"
                id="search"
                placeholder="Pesquisar Livro"
            />
            <i class="fi fi-rr-search" id="searchBtn" title="Pesquisar"></i>

        </div>
        <h6 id="mobileMenu">
            <i class="fi fi-rr-menu-burger" id="menuBtn" title="Menu"></i>
            <div id="mobileMenuContainer">
                    <a href="#" >
                        <i id="profileBtnMobile" class="fi fi-sr-circle-user" title="Perfil"></i>
                    </a>
                    <a href="{% url "bookguardian:newbook"  %}">
                        <i id="addBookbtn" class="fi fi-sr-add" title="Adicionar"></i>
                    </a>
                    <a href="">
                        <i id="homeBtn" class="fi fi-sr-home" title="Inicio"></i>
                    </a>
                    <a href="#">
                        <i id="filterBtnMobile" class="fi fi-sr-filter" title="Filtros"></i>
                    </a>
                    <a href=" {% url "bookguardian:settings"  %}">
                        <i
                            id="configBtn"
                            class="fi fi-sr-settings"
                            title="Configuracoes"
                        ></i>
                    </a>
            </div>
            <div id="subMobileMenu">
                <a href="{%url 'userauths:sign-out'%}">Sair</a>
            </div>
        </h6>
        <h6 id="profileH6">
            <i id="profileBtn" class="fi fi-rr-circle-user" title="Perfil"></i>
            <div id="profileMenuHeader">
                {% if not request.user.is_authenticated %}

                <a href="{% url 'userauths:sing-in' %}">
                    <button id="goToLoginPage">Entrar</button>
                </a>

                <a href="{% url 'userauths:sign-up' %}">
                    <button id="goToRegisterPage">Cadastrar</button>
                </a>

                {% endif %} {% if request.user.is_authenticated %}

                <div id="userNav">
                    <a href="{% url 'userauths:sign-out' %}">
                        <i class="fi fi-rr-exit" id="logout"> Sair</i>
                    </a>
                </div>

                {% endif %}
            </div>
        </h6>
    </div>
    <div id="filter">
        <div>
            <label for="genre">Gênero:</label>
            <select id="genre">
                <option value="">Todos</option>
                <option value="G">Genérico</option>
                <option value="F">Ficção Científica</option>
                <option value="R">Romance</option>
                <option value="T">Terror</option>
                <option value="NF">Não Ficção</option>
                <option value="FA">Fantasia</option>
                <option value="MHQ">Manga e HQ</option>
            </select>
        </div>
        <div>
            <label for="readOrNot">Já leu?</label>
            <select id="readOrNot">
                <option value="">Todos</option>
                <option value="read">Já li</option>
                <option value="nonRead">Não li</option>
            </select>
        </div>
        <button id="applyFilters">Aplicar Filtros</button>
    </div>

</header>
<main>
    <nav id="nav">
        <a href="{% url "bookguardian:newbook"  %}">
            <i id="addBookbtn" class="fi fi-sr-add" title="Adicionar"></i>
        </a>
        <a href="">
            <i id="homeBtn" class="fi fi-sr-home" title="Inicio"></i>
        </a>
        <a href="#">
            <i id="filterBtn" class="fi fi-sr-filter" title="Filtros"></i>
        </a>
        <a href=" {% url "bookguardian:settings"  %}">
            <i
                id="configBtn"
                class="fi fi-sr-settings"
                title="Configuracoes"
            ></i>
        </a>
    </nav>
    <section>
        {% if bookguardian %}
        {% if request.user.is_authenticated %}
        {% for book in bookguardian %}
            <div id="alertMsg" style="display:none"><h1>nenhum item encontrado :(</h1><img src="{% static "assets/img/livroTriste.png" %}" alt="livro triste"></div>
            <a href="{% url 'bookguardian:bookdetail'  pk=book.pk %}" class="card">
                {% if book.read %}
                    <i class="fi fi-sr-bookmark read"></i>
                {% else %}
                    <i class="fi fi-sr-bookmark nonRead"></i>
                {% endif %}
                <img src="{{ book.book_image.url }}" alt="capa" />
                <div class="backCard">
                    <p id="title">{{ book.title }}</p>
                    <p id="autora">{{ book.author_book }}</p>
                    <h4 style="display: none;" id="tag">{{book.category}}</h4>
                </div>
            </a>
        {% endfor %}
        {% endif %}
        {% else %}
        <div id="alertMsg" style="display:flex;margin:0; margin-top:-200px"><h1>nenhum item encontrado :(</h1><img src="{% static "assets/img/livroTriste.png" %}" alt="livro triste"></div>

    {% endif %}

</section>
</main>
{% endblock content %}

bookguardian/templates/ladinpage.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<header>
    <div class="menu">
        <div class="menu__logo">
            <img class="cabecalho-imagem" src="{% static "assets/img/book2.png" %}">
        </div>
        <nav class="nav__list" id="xd">
            <a href="{% url 'userauths:sign-in' %}" class="cabecalho-menu-item2">entrar</a>
            <a href="{% url 'userauths:sign-up' %}" class="cabecalho-menu-item2">cadastrar</a>
        </nav>
    </div>
    <img id="banner" src="{% static "assets/img/Home.png" %}" alt="Home">
</header>

<section id="oque-e" class="somos">
    <h2 class="section__titulo">O que é?</h2>
    <div class="somos-c">
        <div class="somos-c__texto">
            <p class="somos-c__texto2">
                O Bookguardian é um site projetado especificamente para ajudar pessoas como você a organizar suas coleções de livros.
            </p>
            <br>
            <p>Com uma interface intuitiva e recursos inteligentes, ele
            simplifica o gerenciamento do conteúdo de sua biblioteca, tornando a
            experiência de catalogar e encontrar seus livros mais facil.</p>
        </div>
        <div class="somos-c__img">
            <img src="{% static "assets/img/somos.png" %}" alt="Quem somos">
        </div>
    </div>
</section>

<section id="conta-demo" class="cursos">
    <h2 class="section__titulo">Confira Uma Demontração</h2>
    <div class="cursos-c">
        <div class="curso">
            <img src="{% static "assets/img/004--Streamline-Zoo-Office.png" %}"
            alt="Inteligência Artificial" class="curso__img">
            <div class="demo">
                <h3 class="curso__titulo">Email: <span>testdemo@gmail.com</span></h3>
                <h3 class="curso__titulo">Senha: <span>demo1234</span></h3>
            </div>
        </div>
    </div>
</section>

<footer class="footer">
    <div class="footer-c">
        <div class="membros">
            <h3>Equipe</h3>
            <ul>
                <li><a href="https://github.com/Andra-sun/">Camile</a></li>
                <li><a href="https://github.com/wendellast">Wendel</a></li>
                <li><a href="https://github.com/nadox00">Fernando</a></li>
                <li><a href="https://github.com/VilasBoass">Marcos</a></li>
                <li><a href="https://github.com/LuyysHenriqueKuromi">Luis</a></li>
            </ul>
        </div>
        <div class="membros">
            <h3>linguagens</h3>
            <ul>
                <li>Python</li>
                <li>JavaScript</li>
                <li>Html5</li>
                <li>CSS</li>
            </ul>
        </div>
        <div class="membros">
            <h3>Navegação</h3>
            <ul>
                <li><a href="#banner">Capa</a></li>
                <li><a href="#oque-e">O que é?</a></li>
                <li><a href="#conta-demo">Conta demo</a></li>
                <li><a href="{% url 'userauths:sign-in' %}">Login</a></li>
                <li><a href="{% url 'userauths:sign-up' %}"></a></li>
            </ul>
        </div>
    </div>
    <p>Abril 2024</p>
</footer>

{% endblock content %}

bookguardian/templates/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block title %} Login {% endblock title %}
{% block content %}

<div class ="login-container show" id="logincontainer" >
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Nome de Usuário" required>
        <br>
        <input type="password" name="password" placeholder="Senha" required>
        <br>
        <input type="submit" value="Login">
    </form>
    <a href="{% provider_login_url "google" %}?next=/">Login com Google</a>
    <p>Não possui uma conta ? <a href="{% url 'bookguardian:register-user' %}" id="singIn" class="signup-link">Registre-se aqui</a></p>
</div>

{% endblock content %}

bookguardian/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class ="login-container show" id="singincontainer" >
    <h2>Cadastro</h2>
    <form method="POST" action="{% url 'bookguardian:register-user' %}">
        {% csrf_token %}
        {{form.username}}

        {{form.password1}}
        <div id="passwordStatus">
            X Minimo de 6 letras
        </div>

        {{form.password2}}

        <input class="button" type="submit" value="Register" id="registerBtnSubimit">
    </form>

    <p>Ja possui uma conta ? <a href="{% url 'bookguardian:login' %}" id="logIn" class="signup-link">Entre aqui</a></p>
</div>
<script>
    const passwordAlert = document.getElementById("passwordStatus");
    const passwordInput = document.getElementById("password1");
    const password2 = document.getElementById("password2").value;

    passwordInput.addEventListener("input", function() {
        const passwordValue = passwordInput.value;
        passwordAlert.style.display="flex";
        passwordAlert.style.animation="slideDown 10s ease forwards";

        if (passwordValue.length < 6) {
            passwordAlert.innerHTML = "X Mínimo de 6 letras";
            passwordAlert.style.backgroundColor = "#ff41419f";

        } else {
            passwordAlert.innerHTML = "✓ Mínimo de 6 letras";
            passwordAlert.style.backgroundColor = "#57ff419f";
        }
    });
    passwordInput.addEventListener("blur", function() {
        passwordAlert.style.display = "none";
        passwordAlert.style.animation="slideUp 10s ease forwards";

    });
</script>
{% endblock content %}

bookguardian/templates/updateBook.html
{% extends "base.html" %} {% block title %} Adicionar Livro {% endblock title %}
{% block content %}
    <div class="rowContainer">
        <div id="newBookDiv">
            <h2>Editar Livro</h2>
            <form id="newBookForm" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="titleInp">Título:</label>
                <input type="text" id="titleInp" name="title"
                placeholder="Titulo" required value="{{ bookguardian.title }}">

                <label for="authorInp">Autor(a):</label>
                <input type="text" id="authorInp" name="author_book" placeholder="Autor" value="{{ bookguardian.author_book }}">

                <label for="descriptionInp">Descrição:</label>
                <textarea id="descriptionInp" name="description"
                placeholder="Descricao"  rows="4" style="resize: vertical;">{{ bookguardian.description }}</textarea>

                <label for="imageInp">Imagem da capa:</label>
                <input type="file" id="imageInp" name="book_image" value="{{ bookguardian.book_image.url }}">

                <div id="formSelects">
                    <label for="genre">Gênero:</label>
                    <select id="genre" name="category">
                        <option value="G" {% if bookguardian.category == 'G' %} selected {% endif %}>Genérico</option>
                        <option value="F" {% if bookguardian.category == 'F' %} selected {% endif %}>Ficção científica</option>
                        <option value="R" {% if bookguardian.category == 'R' %} selected {% endif %}>Romance</option>
                        <option value="T" {% if bookguardian.category == 'T' %} selected {% endif %}>Terror</option>
                        <option value="NF" {% if bookguardian.category == 'NF' %} selected {% endif %}>Não ficção</option>
                        <option value="FA" {% if bookguardian.category == 'FA' %} selected {% endif %}>Fantasia</option>
                        <option value="MHQ" {% if bookguardian.category == 'MHQ' %} selected {% endif %}>Manga e HQ</option>
                    </select>


                    <label for="status">Status:</label>
                    <select id="status" name="read">
                        <option value="True" {% if bookguardian.read == 'True' %} selected {% endif %}>Já li</option>
                        <option value="False" {% if bookguardian.read == 'False' %} selected {% endif %}>Quero ler</option>
                    </select>
                </div>
                <div id="addBtnsNavegation">
                    <button type="submit" id="addBook">Adicionar</button>
                    <button id="cancelBook">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
    <script>

    </script>
{% endblock content %}